Repository ENCODE-DCC/snovault, pull requests merged in 2018-03, with the labels that each got.

#87 SNO-29 Limit audits on form update
  src/snovault/auditor.py
  src/snovault/elasticsearch/esstorage.py
Labels: in progress

#86 SNO-26 Add schemas map view to profiles
  src/snovault/schema_views.py
Labels: ready to merge

#85 SNO-25 Make uniqueItems to check the serialized values
  src/snovault/schema_utils.py
  src/snovault/tests/test_schema_utils.py
Labels: Pending Encoded Merge, ready to merge

#93 SNO-28 limit ES storage to indices created for snovault resources
  src/snovault/elasticsearch/create_mapping.py
  src/snovault/elasticsearch/esstorage.py
  src/snovault/elasticsearch/interfaces.py
  src/snowflakes/search.py
Labels: ready to merge

#94 SNO-33 Specify index for get_by_unique_key from collection
  src/snovault/connection.py
  src/snovault/elasticsearch/esstorage.py
  src/snovault/resources.py
  src/snovault/storage.py
Labels: In QA
